# Generated by Django 5.2 on 2025-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست ارتباط', 'verbose_name_plural': 'درخواست\u200cهای ارتباط'},
        ),
    ]
