# Generated by Django 5.2 on 2025-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_author_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
