# Generated by Django 5.2 on 2025-04-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تایید شده توسط ادمین'),
        ),
    ]
