# Generated by Django 5.2 on 2025-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_category/', verbose_name='تصویر دسته بندی'),
        ),
    ]
