# Generated by Django 5.2 on 2025-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('project_type', models.CharField(choices=[('web', 'توسعه وب'), ('mobile', 'توسعه موبایل'), ('ai', 'هوش مصنوعی'), ('design', 'طراحی UI/UX'), ('other', 'سایر')], max_length=50, verbose_name='نوع پروژه')),
                ('details', models.TextField(verbose_name='جزئیات پروژه')),
                ('budget', models.CharField(blank=True, help_text='مثلاً 10-15 میلیون تومان یا دلاری', max_length=50, verbose_name='بودجه پیش\u200cنهادی')),
                ('contact_method', models.CharField(choices=[('email', 'ایمیل'), ('phone', 'تماس تلفنی'), ('whatsapp', 'واتساپ'), ('telegram', 'تلگرام')], max_length=50, verbose_name='روش ترجیحی ارتباط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
                'ordering': ['-created_at'],
            },
        ),
    ]
